export const logicalPool = [
  {
    type: "logical",
    subtype: "silogisme",
    category: "Tes Logika",
    text: "Semua karyawan di perusahaan X rajin bekerja. Budi adalah karyawan di perusahaan X. Kesimpulan yang paling tepat adalah...",
    options: [
      "Budi tidak rajin bekerja",
      "Budi rajin bekerja",
      "Budi adalah manajer",
      "Sebagian karyawan rajin bekerja",
      "Tidak dapat disimpulkan",
    ],
    correctIndex: 1,
    explanation:
      "Jika semua karyawan rajin bekerja dan Budi adalah karyawan, maka Budi pasti rajin bekerja.",
    steps: ["Premis 1: semua karyawan rajin", "Premis 2: Budi karyawan", "Kesimpulan: Budi rajin"],
  },
  {
    type: "logical",
    subtype: "silogisme",
    category: "Tes Logika",
    text: "Semua atlet berlatih keras setiap hari. Sebagian atlet adalah pelajar. Kesimpulan yang paling tepat adalah...",
    options: [
      "Semua pelajar berlatih keras",
      "Sebagian pelajar berlatih keras",
      "Semua atlet adalah pelajar",
      "Tidak ada pelajar yang atlet",
      "Pelajar tidak pernah berlatih",
    ],
    correctIndex: 1,
    explanation:
      "Karena sebagian atlet adalah pelajar dan semua atlet berlatih keras, maka sebagian pelajar berlatih keras.",
    steps: ["Semua atlet berlatih keras", "Sebagian atlet pelajar → sebagian pelajar berlatih keras"],
  },
  {
    type: "logical",
    subtype: "logika-formal",
    category: "Tes Logika",
    text: "Jika hari hujan maka jalan menjadi basah. Hari ini hujan. Kesimpulan yang paling tepat adalah...",
    options: [
      "Jalan tidak basah",
      "Jalan basah",
      "Hari ini tidak hujan",
      "Jalan mungkin basah",
      "Tidak dapat disimpulkan",
    ],
    correctIndex: 1,
    explanation: "Modus ponens: Jika P maka Q, dan P benar, maka Q benar. Jalan basah.",
    steps: ["P → Q", "P benar", "Maka Q benar (jalan basah)"],
  },
  {
    type: "logical",
    subtype: "silogisme",
    category: "Tes Logika",
    text: "Tidak ada kucing yang bisa terbang. Semua burung bisa terbang. Kesimpulan yang paling tepat adalah...",
    options: [
      "Semua kucing adalah burung",
      "Kucing bisa terbang",
      "Kucing bukan burung",
      "Burung tidak bisa terbang",
      "Sebagian kucing bisa terbang",
    ],
    correctIndex: 2,
    explanation:
      "Karena kucing tidak bisa terbang sedangkan semua burung bisa terbang, maka tidak ada kucing yang merupakan burung.",
    steps: ["Kucing: tidak terbang", "Burung: terbang", "Maka kucing bukan burung"],
  },
  {
    type: "logical",
    subtype: "sebab-akibat",
    category: "Tes Logika",
    text: "Semakin tinggi suhu ruangan, semakin cepat es mencair. Faktor yang menjadi penyebab mencairnya es pada pernyataan tersebut adalah...",
    options: [
      "Volume es",
      "Suhu ruangan",
      "Jenis es",
      "Waktu",
      "Kelembapan",
    ],
    correctIndex: 1,
    explanation:
      "Pernyataan menunjukkan hubungan sebab-akibat di mana suhu ruangan yang tinggi menyebabkan es mencair lebih cepat.",
  },
  {
    type: "logical",
    subtype: "sebab-akibat",
    category: "Tes Logika",
    text: "Penggunaan media sosial meningkat dan tingkat interaksi tatap muka menurun pada periode yang sama. Kesimpulan yang paling tepat adalah...",
    options: [
      "Media sosial menyebabkan interaksi tatap muka menurun",
      "Interaksi tatap muka menurun pasti karena media sosial",
      "Terdapat korelasi, namun belum tentu hubungan sebab-akibat",
      "Media sosial tidak berpengaruh apa pun",
      "Orang berhenti bersosialisasi sepenuhnya",
    ],
    correctIndex: 2,
    explanation:
      "Dua hal yang terjadi bersamaan belum tentu memiliki hubungan sebab-akibat; bisa saja hanya korelasi.",
  },
  {
    type: "logical",
    subtype: "logika-formal",
    category: "Tes Logika",
    text: "Jika P maka Q. Diketahui bahwa Q tidak benar. Kesimpulan yang paling tepat adalah...",
    options: [
      "P benar",
      "P tidak benar",
      "P dan Q benar",
      "Q benar",
      "Tidak dapat disimpulkan",
    ],
    correctIndex: 1,
    explanation:
      "Modus tollens: Jika P → Q dan Q salah, maka P pasti salah.",
    steps: ["P → Q", "¬Q", "Maka ¬P (P tidak benar)"],
  },
  {
    type: "logical",
    subtype: "logika-formal",
    category: "Tes Logika",
    text: "P atau Q benar (setidaknya salah satu). Diketahui P tidak benar. Kesimpulan yang paling tepat adalah...",
    options: [
      "Q benar",
      "Q tidak benar",
      "P benar",
      "P dan Q benar",
      "Tidak dapat disimpulkan",
    ],
    correctIndex: 0,
    explanation:
      "Disjungsi: jika P atau Q harus benar dan P salah, maka Q harus benar.",
    steps: ["P ∨ Q", "¬P", "Maka Q"],
  },
  {
    type: "logical",
    subtype: "diagram-logika",
    category: "Tes Logika",
    text: "Semua X adalah Y. Semua Y adalah Z. Kesimpulan yang paling tepat adalah...",
    options: [
      "Semua Z adalah X",
      "Semua X adalah Z",
      "Semua Y adalah X",
      "Sebagian Z bukan Y",
      "Tidak dapat disimpulkan",
    ],
    correctIndex: 1,
    explanation:
      "Jika semua X bagian dari Y, dan semua Y bagian dari Z, maka semua X bagian dari Z.",
    steps: ["X ⊆ Y", "Y ⊆ Z", "Maka X ⊆ Z"],
  },
  {
    type: "logical",
    subtype: "analisis-kasus",
    category: "Tes Logika",
    text: "Sebuah tim berhasil menyelesaikan proyek sebelum tenggat waktu, namun laporan pengujian menunjukkan banyak bug yang belum diperbaiki. Langkah paling tepat dilakukan tim adalah...",
    options: [
      "Langsung menyerahkan hasil ke klien",
      "Menambah fitur baru sebelum rilis",
      "Memprioritaskan perbaikan bug sebelum menambah fitur",
      "Mengabaikan bug karena proyek selesai",
      "Menunda semua aktivitas",
    ],
    correctIndex: 2,
    explanation:
      "Bug yang banyak mengancam kualitas produk, sehingga perbaikan bug harus diprioritaskan sebelum penambahan fitur.",
  },
  {
    type: "logical",
    subtype: "silogisme",
    category: "Tes Logika",
    text: "Semua dokter memiliki gelar sarjana. Sebagian lulusan sarjana bekerja di bidang teknologi. Kesimpulan yang paling tepat adalah...",
    options: [
      "Semua dokter bekerja di bidang teknologi",
      "Sebagian dokter bekerja di bidang teknologi",
      "Semua lulusan sarjana adalah dokter",
      "Belum tentu semua dokter bekerja di bidang teknologi",
      "Tidak ada dokter yang berijazah",
    ],
    correctIndex: 3,
    explanation:
      "Informasi bahwa sebagian lulusan sarjana bekerja di teknologi tidak memberi kesimpulan pasti tentang dokter.",
  },
  {
    type: "logical",
    subtype: "silogisme",
    category: "Tes Logika",
    text: "Jika ujian akan diadakan maka ruangan ujian disiapkan. Ruangan ujian tidak disiapkan. Kesimpulan yang paling tepat adalah...",
    options: [
      "Ujian tetap diadakan",
      "Ujian tidak diadakan",
      "Ruangan tetap disiapkan",
      "Ujian diadakan tanpa ruangan",
      "Tidak dapat disimpulkan",
    ],
    correctIndex: 1,
    explanation:
      "Modus tollens: karena konsekuensinya (ruangan disiapkan) tidak terjadi, maka sebabnya (ujian) tidak terjadi.",
    steps: ["Ujian → ruangan siap", "Ruangan tidak siap", "Maka ujian tidak diadakan"],
  },
  {
    type: "logical",
    subtype: "sebab-akibat",
    category: "Tes Logika",
    text: "Produktivitas karyawan menurun setelah perusahaan memberlakukan kebijakan lembur wajib selama sebulan. Kesimpulan yang paling tepat adalah...",
    options: [
      "Lembur wajib pasti menyebabkan penurunan produktivitas",
      "Lembur wajib menyebabkan kenaikan produktivitas",
      "Penurunan produktivitas bisa berkaitan dengan kebijakan, tapi perlu analisis lebih lanjut",
      "Karyawan tidak mau bekerja",
      "Perusahaan harus lembur lebih banyak",
    ],
    correctIndex: 2,
    explanation:
      "Data korelasional belum cukup untuk menyimpulkan sebab-akibat; perlu analisis faktor lain seperti kelelahan dan kualitas pengukuran.",
  },
  {
    type: "logical",
    subtype: "sebab-akibat",
    category: "Tes Logika",
    text: "Iklan perusahaan meningkat dan penjualan juga meningkat dalam tiga bulan berturut-turut. Pernyataan yang paling hati-hati adalah...",
    options: [
      "Iklan terbukti menjadi satu-satunya penyebab kenaikan penjualan",
      "Ada kaitan antara iklan dan penjualan, namun perlu data lanjutan",
      "Penjualan naik tanpa pengaruh iklan",
      "Iklan harus dihentikan agar penjualan lebih tinggi",
      "Tidak ada hubungan apa pun",
    ],
    correctIndex: 1,
    explanation:
      "Kenaikan bersamaan tidak membuktikan kausalitas tunggal; kesimpulan yang hati-hati adalah terdapat kaitan yang perlu diverifikasi.",
  },
  {
    type: "logical",
    subtype: "logika-formal",
    category: "Tes Logika",
    text: "Jika seseorang lulus tes TOEFL maka ia diterima sebagai staf internasional. Budi diterima sebagai staf internasional. Kesimpulan yang paling tepat adalah...",
    options: [
      "Budi pasti lulus tes TOEFL",
      "Budi tidak lulus tes TOEFL",
      "Belum tentu Budi lulus tes TOEFL",
      "Semua staf internasional lulus TOEFL",
      "Budi gagal seleksi",
    ],
    correctIndex: 2,
    explanation:
      "Lulus TOEFL adalah syarat cukup, bukan syarat satu-satunya. Diterimanya Budi tidak membuktikan ia lulus TOEFL.",
    steps: ["TOEFL → diterima", "Diterima", "Maka belum tentu TOEFL (fallacy affirming consequent)"],
  },
  {
    type: "logical",
    subtype: "logika-formal",
    category: "Tes Logika",
    text: "Jika P maka Q. Diketahui P benar. Kesimpulan yang paling tepat adalah...",
    options: [
      "Q benar",
      "Q tidak benar",
      "P tidak benar",
      "P dan Q salah",
      "Tidak dapat disimpulkan",
    ],
    correctIndex: 0,
    explanation: "Modus ponens: P benar dan P → Q, maka Q benar.",
    steps: ["P → Q", "P", "Maka Q"],
  },
  {
    type: "logical",
    subtype: "analisis-kasus",
    category: "Tes Logika",
    text: "Seorang kasir menemukan selisih uang di akhir shift. Langkah pertama yang paling tepat dilakukan adalah...",
    options: [
      "Menutup kekurangan dari uang pribadi",
      "Menghitung ulang dan mencocokkan dengan transaksi",
      "Menyalahkan rekan kerja",
      "Mengabaikan selisih tersebut",
      "Langsung melaporkan tanpa pemeriksaan",
    ],
    correctIndex: 1,
    explanation:
      "Langkah paling objektif adalah menghitung ulang dan menelusuri transaksi untuk menemukan sumber selisih.",
  },
  {
    type: "logical",
    subtype: "silogisme",
    category: "Tes Logika",
    text: "Semua buah mengandung vitamin. Apel adalah buah. Kesimpulan yang paling tepat adalah...",
    options: [
      "Apel tidak mengandung vitamin",
      "Apel mengandung vitamin",
      "Semua yang mengandung vitamin adalah apel",
      "Sebagian apel tidak mengandung vitamin",
      "Tidak dapat disimpulkan",
    ],
    correctIndex: 1,
    explanation:
      "Karena semua buah mengandung vitamin dan apel adalah buah, maka apel mengandung vitamin.",
    steps: ["Semua buah → vitamin", "Apel → buah", "Apel → vitamin"],
  },
  {
    type: "logical",
    subtype: "silogisme",
    category: "Tes Logika",
    text: "Tidak ada logam yang berwujud cair pada suhu ruangan, kecuali raksa. Zat X berwujud cair pada suhu ruangan. Kesimpulan yang paling tepat adalah...",
    options: [
      "Zat X pasti bukan logam",
      "Zat X adalah logam",
      "Zat X mungkin adalah raksa",
      "Zat X pasti raksa",
      "Tidak ada logam cair",
    ],
    correctIndex: 2,
    explanation:
      "Karena satu-satunya logam cair adalah raksa, zat X yang cair bisa jadi raksa, namun bisa juga zat non-logam.",
  },
  {
    type: "logical",
    subtype: "diagram-logika",
    category: "Tes Logika",
    text: "Sebagian siswa gemar matematika. Semua siswa yang gemar matematika rajin belajar. Kesimpulan yang paling tepat adalah...",
    options: [
      "Semua siswa rajin belajar",
      "Sebagian siswa rajin belajar",
      "Semua yang rajin belajar gemar matematika",
      "Tidak ada siswa yang rajin belajar",
      "Tidak dapat disimpulkan",
    ],
    correctIndex: 1,
    explanation:
      "Sebagian siswa gemar matematika dan mereka rajin belajar, sehingga sebagian siswa rajin belajar.",
    steps: ["Sebagian siswa → matematika", "Gemar matematika → rajin", "Sebagian siswa rajin"],
  },
  {
    type: "logical",
    subtype: "sebab-akibat",
    category: "Tes Logika",
    text: "Setelah perusahaan melakukan rekrutmen massal, kualitas rata-rata karyawan baru dinilai lebih rendah dalam evaluasi tahunan. Pernyataan yang paling tepat adalah...",
    options: [
      "Rekrutmen massal pasti menurunkan kualitas",
      "Semua karyawan baru berkualitas rendah",
      "Perlu evaluasi proses seleksi untuk memastikan penyebabnya",
      "Rekrutmen massal meningkatkan kualitas",
      "Karyawan lama lebih buruk",
    ],
    correctIndex: 2,
    explanation:
      "Hubungan ini perlu diselidiki melalui evaluasi proses seleksi, bukan langsung menyimpulkan sebab-akibat.",
  },
  {
    type: "logical",
    subtype: "logika-formal",
    category: "Tes Logika",
    text: "Jika seseorang makan makanan pedas maka perutnya terasa sakit. Andi tidak makan makanan pedas. Kesimpulan yang paling tepat adalah...",
    options: [
      "Perut Andi pasti sakit",
      "Perut Andi pasti tidak sakit",
      "Belum tentu perut Andi tidak sakit",
      "Andi makan pedas",
      "Andi tidak mungkin sakit perut",
    ],
    correctIndex: 2,
    explanation:
      "Makan pedas hanyalah salah satu penyebab sakit perut. Tanpa makan pedas, perut bisa saja sakit karena sebab lain.",
  },
  {
    type: "logical",
    subtype: "silogisme",
    category: "Tes Logika",
    text: "Semua anggota koperasi rutin menabung. Sinta tidak menabung. Kesimpulan yang paling tepat adalah...",
    options: [
      "Sinta adalah anggota koperasi",
      "Sinta bukan anggota koperasi",
      "Semua penabung adalah anggota koperasi",
      "Sinta menabung",
      "Tidak dapat disimpulkan",
    ],
    correctIndex: 1,
    explanation:
      "Karena semua anggota menabung dan Sinta tidak menabung, maka Sinta bukan anggota koperasi.",
    steps: ["Anggota → menabung", "Sinta: tidak menabung", "Sinta bukan anggota"],
  },
  {
    type: "logical",
    subtype: "analisis-kasus",
    category: "Tes Logika",
    text: "Seorang klien mengeluh produk yang dikirim dalam keadaan rusak. Prioritas tindakan yang paling tepat adalah...",
    options: [
      "Menolak klaim klien",
      "Menyalahkan pihak ekspedisi",
      "Mengganti produk dan mengevaluasi sistem pengemasan",
      "Mengabaikan keluhan",
      "Menunda semua pengiriman",
    ],
    correctIndex: 2,
    explanation:
      "Penyelesaian terbaik adalah mengganti produk sebagai solusi jangka pendek dan memperbaiki pengemasan untuk jangka panjang.",
  },
  {
    type: "logical",
    subtype: "silogisme",
    category: "Tes Logika",
    text: "Semua peneliti bersikap teliti. Sebagian orang yang teliti adalah pustakawan. Kesimpulan yang paling tepat adalah...",
    options: [
      "Semua peneliti adalah pustakawan",
      "Sebagian orang teliti adalah peneliti",
      "Semua pustakawan adalah peneliti",
      "Tidak ada peneliti yang teliti",
      "Tidak dapat disimpulkan",
    ],
    correctIndex: 1,
    explanation:
      "Karena semua peneliti teliti, maka sebagian orang yang teliti pastinya mencakup para peneliti.",
  },
  {
    type: "logical",
    subtype: "logika-formal",
    category: "Tes Logika",
    text: "Jika sistem komputer bermasalah maka laporan menjadi terlambat. Laporan hari ini tepat waktu. Kesimpulan yang paling tepat adalah...",
    options: [
      "Sistem komputer bermasalah",
      "Sistem komputer tidak bermasalah",
      "Laporan tetap terlambat",
      "Tidak dapat disimpulkan",
      "Sistem baik tapi laporan terlambat",
    ],
    correctIndex: 1,
    explanation:
      "Modus tollens: jika konsekuensi (laporan terlambat) tidak terjadi, maka sebab (sistem bermasalah) tidak terjadi.",
    steps: ["Bermasalah → terlambat", "Tidak terlambat", "Maka tidak bermasalah"],
  },
  {
    type: "logical",
    subtype: "sebab-akibat",
    category: "Tes Logika",
    text: "Jumlah kecelakaan lalu lintas menurun setelah perbaikan penerangan jalan di kawasan tersebut. Kesimpulan yang paling tepat adalah...",
    options: [
      "Penerangan pasti satu-satunya penyebab penurunan",
      "Perbaikan penerangan berkontribusi pada penurunan kecelakaan",
      "Kecelakaan meningkat",
      "Penerangan tidak berpengaruh",
      "Pengemudi menjadi lebih buruk",
    ],
    correctIndex: 1,
    explanation:
      "Perbaikan penerangan adalah salah satu faktor yang wajar berkontribusi, meski perlu data tambahan untuk memastikan.",
  },
  {
    type: "logical",
    subtype: "diagram-logika",
    category: "Tes Logika",
    text: "Semua P adalah Q. Sebagian R adalah P. Kesimpulan yang paling tepat adalah...",
    options: [
      "Semua R adalah Q",
      "Sebagian R adalah Q",
      "Semua Q adalah P",
      "Tidak ada R yang Q",
      "Semua P adalah R",
    ],
    correctIndex: 1,
    explanation:
      "Sebagian R adalah P, dan semua P adalah Q, sehingga sebagian R adalah Q.",
    steps: ["R ∩ P ≠ ∅", "P ⊆ Q", "Maka R ∩ Q ≠ ∅ (sebagian R adalah Q)"],
  },
  {
    type: "logical",
    subtype: "analisis-kasus",
    category: "Tes Logika",
    text: "Dua orang anggota tim berselisih pendapat mengenai pendekatan penyelesaian proyek. Tindakan manajer yang paling tepat adalah...",
    options: [
      "Memihak salah satu anggota",
      "Mendengarkan keduanya secara objektif lalu memutuskan bersama",
      "Mengabaikan konflik",
      "Memecat salah satu anggota",
      "Menunda proyek selamanya",
    ],
    correctIndex: 1,
    explanation:
      "Manajer yang baik mendengar semua pihak secara objektif dan melibatkan tim dalam pengambilan keputusan.",
  },
  {
    type: "logical",
    subtype: "silogisme",
    category: "Tes Logika",
    text: "Semua pelanggan yang puas akan kembali membeli. Rudi membeli kembali. Kesimpulan yang paling tepat adalah...",
    options: [
      "Rudi pasti puas",
      "Belum tentu Rudi puas",
      "Rudi tidak puas",
      "Semua pembeli puas",
      "Tidak ada yang membeli kembali",
    ],
    correctIndex: 1,
    explanation:
      "Kepuasan adalah salah satu penyebab pembelian ulang, namun belum tentu satu-satunya.",
  },
];